/**
 * AnchorMarket.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CancelGroupMarketCommand {
    'marketId': string;
    'requestingUserId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "requestingUserId",
            "baseName": "requestingUserId",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return CancelGroupMarketCommand.attributeTypeMap;
    }

    public constructor() {
    }
}
