/**
 * AnchorMarket.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LimitOrderPrice } from '../models/LimitOrderPrice';
import { Market } from '../models/Market';
import { Outcome } from '../models/Outcome';
import { TradeExecution } from '../models/TradeExecution';
import { HttpFile } from '../http/http';

export class LimitOrder {
    'marketId'?: string;
    'outcomeId'?: string;
    'userId'?: string;
    'side'?: number;
    'price'?: LimitOrderPrice;
    'quantity'?: LimitOrderPrice;
    'filledQuantity'?: LimitOrderPrice;
    'totalCost'?: LimitOrderPrice;
    'type'?: number;
    'status'?: number;
    'expiresAt'?: Date | null;
    'market'?: Market;
    'outcome'?: Outcome;
    'tradeExecutions'?: Array<TradeExecution>;
    'id'?: string;
    'createdAt'?: Date;
    'updatedAt'?: Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "outcomeId",
            "baseName": "outcomeId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "number",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "filledQuantity",
            "baseName": "filledQuantity",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "totalCost",
            "baseName": "totalCost",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "market",
            "baseName": "market",
            "type": "Market",
            "format": ""
        },
        {
            "name": "outcome",
            "baseName": "outcome",
            "type": "Outcome",
            "format": ""
        },
        {
            "name": "tradeExecutions",
            "baseName": "tradeExecutions",
            "type": "Array<TradeExecution>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return LimitOrder.attributeTypeMap;
    }

    public constructor() {
    }
}
