/**
 * AnchorMarket.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LimitOrderPrice } from '../models/LimitOrderPrice';
import { TradeExecutionDto } from '../models/TradeExecutionDto';
import { HttpFile } from '../http/http';

export class LimitOrderDetailDto {
    'id': string;
    'marketId': string;
    'marketTitle': string;
    'outcomeId': string;
    'outcomeTitle': string;
    'userId': string;
    'side': number;
    'price': LimitOrderPrice;
    'quantity': LimitOrderPrice;
    'filledQuantity': LimitOrderPrice;
    'remainingQuantity': LimitOrderPrice;
    'averageFillPrice': LimitOrderPrice;
    'totalCost': LimitOrderPrice;
    'type': number;
    'status': number;
    'expiresAt': Date | null;
    'createdAt': Date;
    'updatedAt': Date | null;
    'tradeExecutions': Array<TradeExecutionDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "marketTitle",
            "baseName": "marketTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "outcomeId",
            "baseName": "outcomeId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "outcomeTitle",
            "baseName": "outcomeTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "number",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "filledQuantity",
            "baseName": "filledQuantity",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "remainingQuantity",
            "baseName": "remainingQuantity",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "averageFillPrice",
            "baseName": "averageFillPrice",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "totalCost",
            "baseName": "totalCost",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "tradeExecutions",
            "baseName": "tradeExecutions",
            "type": "Array<TradeExecutionDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LimitOrderDetailDto.attributeTypeMap;
    }

    public constructor() {
    }
}
