/**
 * AnchorMarket.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LimitOrderPrice } from '../models/LimitOrderPrice';
import { HttpFile } from '../http/http';

export class MarketPriceDto {
    'marketId': string;
    'marketTitle': string;
    'outcomeId': string;
    'outcomeTitle': string;
    'currentPrice': LimitOrderPrice;
    'previousPrice': LimitOrderPrice;
    'change24h': LimitOrderPrice;
    'change24hPercent': LimitOrderPrice;
    'high24h': LimitOrderPrice;
    'low24h': LimitOrderPrice;
    'volume24h': LimitOrderPrice;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "marketTitle",
            "baseName": "marketTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "outcomeId",
            "baseName": "outcomeId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "outcomeTitle",
            "baseName": "outcomeTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "currentPrice",
            "baseName": "currentPrice",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "previousPrice",
            "baseName": "previousPrice",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "change24h",
            "baseName": "change24h",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "change24hPercent",
            "baseName": "change24hPercent",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "high24h",
            "baseName": "high24h",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "low24h",
            "baseName": "low24h",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "volume24h",
            "baseName": "volume24h",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return MarketPriceDto.attributeTypeMap;
    }

    public constructor() {
    }
}
