/**
 * AnchorMarket.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Market } from '../models/Market';
import { Outcome } from '../models/Outcome';
import { HttpFile } from '../http/http';

export class MarketResolution {
    'marketId'?: string;
    'winningOutcomeId'?: string;
    'resolvedById'?: string;
    'resolvedAt'?: Date;
    'market'?: Market;
    'winningOutcome'?: Outcome;
    'id'?: string;
    'createdAt'?: Date;
    'updatedAt'?: Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "winningOutcomeId",
            "baseName": "winningOutcomeId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "resolvedById",
            "baseName": "resolvedById",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "resolvedAt",
            "baseName": "resolvedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "market",
            "baseName": "market",
            "type": "Market",
            "format": ""
        },
        {
            "name": "winningOutcome",
            "baseName": "winningOutcome",
            "type": "Outcome",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return MarketResolution.attributeTypeMap;
    }

    public constructor() {
    }
}
