/**
 * AnchorMarket.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LimitOrderPrice } from '../models/LimitOrderPrice';
import { OrderBookDtoBestBid } from '../models/OrderBookDtoBestBid';
import { OrderBookLevelDto } from '../models/OrderBookLevelDto';
import { HttpFile } from '../http/http';

export class OrderBookDto {
    'marketId': string;
    'marketTitle': string;
    'outcomeId': string;
    'outcomeTitle': string;
    'bids': Array<OrderBookLevelDto>;
    'asks': Array<OrderBookLevelDto>;
    'bestBid': OrderBookDtoBestBid | null;
    'bestAsk': OrderBookDtoBestBid | null;
    'spread': LimitOrderPrice;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "marketTitle",
            "baseName": "marketTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "outcomeId",
            "baseName": "outcomeId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "outcomeTitle",
            "baseName": "outcomeTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "bids",
            "baseName": "bids",
            "type": "Array<OrderBookLevelDto>",
            "format": ""
        },
        {
            "name": "asks",
            "baseName": "asks",
            "type": "Array<OrderBookLevelDto>",
            "format": ""
        },
        {
            "name": "bestBid",
            "baseName": "bestBid",
            "type": "OrderBookDtoBestBid",
            "format": ""
        },
        {
            "name": "bestAsk",
            "baseName": "bestAsk",
            "type": "OrderBookDtoBestBid",
            "format": ""
        },
        {
            "name": "spread",
            "baseName": "spread",
            "type": "LimitOrderPrice",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return OrderBookDto.attributeTypeMap;
    }

    public constructor() {
    }
}
